### ISSUE TITLE
[main.py] Issues of process_twitter_recommendation()

### ISSUE THREAD

**Issue by MrHohn** [MrHohn/MovieRecommend#2]
The username is actually not passed into the function. When I try to print the username directly, I got empty string.

Some movies do not have available URL, and I encounterred this error:
λ python main.py
[mongo] Initializing database: [imdb]
[MovieRecommend] Target user screen_name: BrunoMars
[MovieRecommend] Profile retrieved.
[MovieRecommend] Built up actors pool, size: 55741
[MovieRecommend] Found 27 actors from profile.
[MovieRecommend] Built up tags pool, size: 1128
[MovieRecommend] Found 59 tags from hashtags.
[MovieRecommend] Found 8876 candidate movies.
[MovieRecommend] Earned recommendations for Twitter.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 869, in run
    self._target(_self._args, *_self._kwargs)
  File "main.py", line 466, in download_coverart
    coverart = urllib.request.urlretrieve(result["Poster"], localpath)
  File "C:\Python34\lib\urllib\request.py", line 178, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 440, in open
    req = Request(fullurl, data)
  File "C:\Python34\lib\urllib\request.py", line 258, in __init__
    self.full_url = url
  File "C:\Python34\lib\urllib\request.py", line 284, in full_url
    self._parse()
  File "C:\Python34\lib\urllib\request.py", line 313, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'N/A'

**Comment by AndrewFM** [comment]
Okay, these are both fixed now.
